### ISSUE TITLE
how to convert single/double quoted strings with variables to backticks with template literals

### ISSUE THREAD

**Issue by cachrisman** [adiessl/vscode-backtix#3]
When you've got a string like this
```
'/services/data/'+API_VERSION+'/sobjects/'+objectName+'/' + externalIdField+'/'
```
how do you convert this into
```
`/services/data/${API_VERSION}/sobjects/${objectName}/${externalIdField}/`
```

Am I missing something?

**Comment by adiessl** [comment]
BacktiX does not support concatenating strings and variables into one template literal at the moment. I might have a look into including an option for this in the future though as that seems to be an interesting additional feature to have. 

I'm not sure when I'll find time for this though, so a PR is also welcome.

**Comment by adiessl** [comment]
With the release of VS Code 1.43 it is now possible to achieve what you are looking for without having to install any extension, see https://code.visualstudio.com/updates/v1_43#_convert-to-template-string-refactoring.
