### ISSUE TITLE
Options to disable quick fix / trigger with command

### ISSUE THREAD

**Issue by ericbf** [adiessl/vscode-backtix#4]
So I'm trying to just trigger toggling between quotes using a command and hiding the quick fix "...". Any thoughts? Right now there is a "contributed command" that fails when you try to run it:

<img width="467" alt="Screen Shot 2019-08-09 at 10 30 02 PM" src="https://user-images.githubusercontent.com/2483476/62816448-bbade380-baf5-11e9-9ac6-4d9fc0106fc7.png">

**Comment by adiessl** [comment]
I specifically created BacktiX to have quick fixes for toggling between quote types as I could only find extensions that achieved the same functionality by using commands – which I find a bit cumbersome in this use case.

So why is there a contributed command then? Well, that was probably left over by accident when starting from the sample project ...

I will try to have a look into including an option to disable the quick fixes and including commands.

**Comment by ericbf** [comment]
Makes sense :). I liked your plugin the most because it does the best job of escaping/unescaping variables. That would be awesome!!

**Comment by ericbf** [comment]
Also because yours lets us disable a quote we don't ever want to use – I only use doubles and backticks in my projects, so that option was must for me. I didn't want to ever cycle to single quotes :D

**Comment by ericbf** [comment]
The end goal is to assign the command to a keystroke (maybe cmd/ctrl-') which would quickly toggle between double quotes and backticks, while also escaping variables correctly (which other plugins did not do, from my testing).

**Comment by adiessl** [comment]
It took some time, but it is finally here: version 2.0.0 of `BackTix` now contributes dedicated commands for converting strings and adding placeholders. These can either be accessed via the command palette or by mapping them to a keyboard shortcut.

The commands still rely on the information of the quick fixes though – therefore it is not possible to disable them. I hope you don't mind and are still using the extension.
