### ISSUE TITLE
This is an awesome extension for JS devs.  Thanks!

### ISSUE THREAD

**Issue by ariestav** [adiessl/vscode-backtix#6]
You can close this issue, but I just wanted to note that this little extension save so much time.  Thank you for making it and sharing it!

**Comment by ariestav** [comment]
Also, just curious, is there any way to disable the `...` that appears in VSCode for each and every string?

**Comment by adiessl** [comment]
Thank you for your kind words, @ariestav, I am glad you find this extension as useful as I do.

Regarding your question: have a look at #5 and my answer there.
